### ISSUE TITLE
No HTTP port found when deploying to render

### ISSUE THREAD

**Issue by SwiftDev29** [m0t9/tg-openai-binder#9]
Error when deploying to render saying no http port found

**Comment by wensiet** [comment]
Traceback, please

**Comment by wensiet** [comment]
If you are trying to enable proxy, make sure that .env has this format:

PROXY=http://username:password@proxy-host:proxy-port

**Comment by wensiet** [comment]
Works, for me on render.com, I used deployment from a git repo.

**Comment by wensiet** [comment]
I see now, render's web-service type requires 10000 port to be opened

**Comment by wensiet** [comment]
https://github.com/m0t9/tg-openai-binder/pull/11

**Comment by wensiet** [comment]
You are welcome, also do not forget to include new .env variable: `ENABLE_RENDER`, just set it to True.
